# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '393f2e682a45424cc487ed81d40cf68b'
  config.secret_key = 'cb195fc8aa9f3baa8cdcb52dca524b9c'
  config.default_from = 'contact@mytripsies.herokuapp.com'

end
